### ISSUE TITLE
Target line in "Year progression" is not removed from chart after deleting target

### ISSUE THREAD

**Issue by djaguszewski** [thomaschampagne/elevate#715] opened 2018-12-20 08:02 UTC
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: 6.8.0 Stable
  * Chrome/Opera/Chromium version: Chrome 71.0.3578.98 (64-bit)
  * OS version: Windows 10
  
### Step 3: Describe the problem:
When the target line is visible on chart and I delete the target, the line is still on and in the table on the right side, Elevate still shows the calculations for deleted target.

#### Steps to reproduce:

  1. Define target (running)
  2. Load the target to the chart
  3. Delete the target
  
#### Actual Behavior:
Target line is still visible on the chart. Elevate still displays calculations for the target in the table on the right side of the chart.
Additionally, it is not possible to unload the target, once it was loaded. I can only replace one target with another one.
  
#### Expected Behavior:

Target is unloaded. The line is not shown on chart any more.
  
#### Media attachement:

![image](https://user-images.githubusercontent.com/6430294/50271744-eac3f780-0435-11e9-97ad-83fee69e1dda.png)

**Comment by dlh3** [comment] 2019-01-02 08:18
This was a duplicate of #702 and was fixed in commit 94d829788d0b6bce52699bc539cec7e312d3e2d6.  Closing as resolved.

**Closed by dlh3** 2019-01-02 08:18 UTC
