### ISSUE TITLE
Old graph had 2 features missing in new Elevate App

### ISSUE THREAD

**Issue by bkleingoldewijk** [thomaschampagne/elevate#762] opened 2019-02-07 07:51 UTC
Plugin version: 6.9.0 Stable
Angular Core version: 7.2.3
Angular Material version: 7.2.2
D3js version: 5.8.0
Chrome: 71.0.3578.98 (Official Build) (64-bit)
OS version: Windows 7
 
The old graph on the profile page is replaced by the Elevate App Year Progressions.
The old graph had 2 great features: "distance last 30 days" and "distance since last year"
  
I hope you will return this feature, maybe with one improvement, use 28 instead of 30 days as most people exersice on the same day every week, so a multifold of 7 makes more sense I think.

Bob klein Goldewijk (donor)

**Comment by thomaschampagne** [comment] 2019-02-07 08:29
@bkleingoldewijk Yes you right. Duplicate of https://github.com/thomaschampagne/elevate/issues/760

Features will come back better old ones ;)

If you want to bring back the old feature you can still download an old build here: https://thomaschampagne.github.io/elevate/#/builds (with filters **branch: master, version: 6.8.1**)

**Comment by thomaschampagne** [comment] 2019-02-27 11:52
closed by #760

**Closed by thomaschampagne** 2019-02-27 11:52 UTC
Labels: block, duplicate
