### ISSUE TITLE
Weighted Average Power Not Matching TrainingPeaks

### ISSUE THREAD

**Issue by malarickk** [thomaschampagne/elevate#673] opened 2018-10-27 14:21 UTC
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: 6.7.0 Stable
  * Chrome/Opera/Chromium version: Version: Chrome 69.0.3497.100 (Official Build) (64-bit)
  * OS version: Mac 10.14
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be usefull to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by thomaschampagne** [comment] 2018-10-27 17:01
@malarickk That's all? :) Any infos, details?

**Comment by malarickk** [comment] 2018-10-27 18:31
Sorry. Just noticed since one of the recent updates the power numbers are off relative to TP. Previously they matched exactly. 

https://www.strava.com/activities/1923673793 <https://www.strava.com/activities/1923673793>

For example Elevate gives a WAP of 214 for this ride but TP gives an NP of 221. Elevate gives a PSS of 84, TP gives TSS of 90.



Happy to provide more info, files etc. just let me know what you need.

Thanks for making Elevate!

-Keith

**Comment by aprokop** [comment] 2018-11-19 05:51
Can be a duplicate of #658.

**Comment by thomaschampagne** [comment] 2018-12-06 10:08
@malarickk Try to clear history an resync to see if #648 solves your problem

**Comment by malarickk** [comment] 2018-12-06 11:09
Thanks!

**Comment by thomaschampagne** [comment] 2018-12-22 15:18
@malarickk I consider this ticket closed. If not please re-open it :)

**Closed by thomaschampagne** 2018-12-22 15:18 UTC
