### ISSUE TITLE
fatigue and form raise in same direction

### ISSUE THREAD

**Issue by johnny-str** [thomaschampagne/elevate#695] opened 2018-11-17 18:43 UTC
### Step 2: Describe your environment

  * Plugin version: 6.7
  * Chrome/
  * OS version: windows 10
  
### Step 3: Describe the problem:
Hi,
FRom september, in my activities the fatigue and form have day by day the same sign, what is not correct. Today my bike activity produce a increase of +3.5 in fitness, +18.7 in fatigue and +8.7 in form.  It seem to me not correct. It's ok ?
thanks
joao

![image](https://user-images.githubusercontent.com/17263090/48664564-6548d280-ea98-11e8-955b-39e3494e04ea.png)

**Comment by thomaschampagne** [comment] 2018-11-17 18:54
Duplicate of #691 and many others
Normal behaviour

**Closed by thomaschampagne** 2018-11-17 18:54 UTC

**Comment by johnny-str** [comment] 2018-11-17 22:00
Hi,
I’m sorry but you this is a mistake. 
Graph in TrainingPeaks and wok+, are   Like old stravistix.
I attach, Wattsboard picture, and you can see exactly the reverse pattern of form and fatigue, what’s don’t have in elevate.
If you want confirmation I can sent you Wko+ (pay software packages from TrainingPeaks)

**Comment by thomaschampagne** [comment] 2018-11-17 22:24
Hi @johnny-str 

Can't see your picture :(  You may reply from github directly i think.

TP calculates form based from yesterday fitness and fatigue as explained here: https://help.trainingpeaks.com/hc/en-us/articles/204071764-Form-TSB-

We got deep discussions on that with other users: Screenshots from TP and Goldencheetah are confirming this.

Thanks, 

Tom

**Comment by johnny-str** [comment] 2018-11-17 23:49
I accept your request, but other sites may write in one form and calculate from another (by mistake in explanation or other intent). But if you think more senses of the athletes at the end of a workout, if you feel fatigued you can not feel that the form has increased. If I rest (- fatigue) I feel more capable (+ form). all the other athletes who have already done this repair, felt their sensations reflected in the line of form, as it was before.
Thanks

**Comment by johnny-str** [comment] 2018-11-17 23:50
Hi
I accept your request, but other sites may write in one form and calculate from another (by mistake in explanation or other intent). But if you think more senses of the athletes at the end of a workout, if you feel fatigued you can not feel that the form has increased. If I rest (- fatigue) I feel more capable (+ form). all the other athletes who have already done this repair, felt their sensations reflected in the line of form, as it was before.
Thanks
