### ISSUE TITLE
Ride stress scores have disappeared

### ISSUE THREAD

**Issue by laurahicks30** [thomaschampagne/elevate#771] opened 2019-02-18 07:48 UTC
Describe your environment

  * Plugin version: Plugin version: 6.9.1 Stable
  * Chrome/Opera/Chromium version: 72.0.3626.109 (Official Build) (64-bit)
  * OS version: Mac OSX
  

Ride Stress Scores have disappeared. Running ones still there. Have tried resyncing and clear resync but no difference. No changes made to any other settings.

**Comment by thomaschampagne** [comment] 2019-02-18 08:34
Duplicate of https://github.com/thomaschampagne/elevate/issues/768
I'm on it.  Working this weekend and night on it for a patch
Thanks for your patience

**Closed by thomaschampagne** 2019-02-18 08:34 UTC
Labels: duplicate
