### ISSUE TITLE
Distance unit options now that yearly progressions have moved

### ISSUE THREAD

**Issue by DaveHaygarth** [thomaschampagne/elevate#372] opened 2017-03-24 09:14 UTC
**Bug description:** 
No way for me to change preferences to miles in the plugin? ALways shows KM
**Actual Behavior:** 
No way for me to change preferences to miles in the plugin? ALways shows KM
**Expected Behavior:** 
Option to display units in Miles
**Steps to Reproduce:** 
- ...Navigate to /yearsProgress 
 - ...Try to change units 
 - ...

**Chrome version** 

**Plugin version:** 

**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by mbartenschlag** [comment] 2017-04-30 19:16
This may be a duplicate of #366.

**Comment by sideee** [comment] 2017-08-04 17:48
Was this ever resolved?

**Comment by mbartenschlag** [comment] 2017-08-04 18:25
It doesn't appear so. :\

**Comment by stiplady** [comment] 2017-09-13 16:12
@thomaschampagne I may take a look at this one if I get a chance in the next couple of days. I know you've approved some of my amends in the past so hopefully my code style is ok for you. I'm thinking just to add another drop down in the list, for "Distance (miles)" (and maybe the same for elevation while I'm in the code?).

Let me know if you'd prefer to have it as a config option in the settings, rather than an extra item in the dropdown, this might actually make more sense, but would probably involve more work to get all relevant distance measurements across the entire plugin to work...

**Closed** 2020-10-21 03:03 UTC
Labels: wontfix
