### ISSUE TITLE
1247 strava activities syncing for the last 3 weeks and still busy

### ISSUE THREAD

**Issue by mslucass** [thomaschampagne/elevate#1083] opened 2022-01-31 08:08 UTC
No error message but I get a 
"Please continue your synchronization in 4~5 hours: you have reached the quota of activities which can be synced at the moment. Of course already synced activities will not be re-synced on next sync.

This limit is intended to avoid Strava servers errors or potential overload."

I get this every 5 hours for the last 3 weeks with trying to sync all my activities. He will start everytime from the beginning.

This is in Chrome
F12 debug screen in the attachment

![strava](https://user-images.githubusercontent.com/20923229/151758709-5de50d2d-fcd2-4e23-9bad-d7dd4427bf67.PNG)

**Comment by thomaschampagne** [comment] 2022-03-04 13:46
Duplicate of #1080 
Download desktop app (beta) instead: https://thomaschampagne.github.io/elevate-docs/

**Closed by thomaschampagne** 2022-03-04 13:46 UTC
