### ISSUE TITLE
Form curve doesn't work. Form is supposed to be the difference between fatigue and fitness but it's not. My fitness will be 92.8 and fatigue 99, and my form -15, then next day fitness stays and fatigue goes to 105 and form improves? makes no sense

### ISSUE THREAD

**Issue by jernejma** [thomaschampagne/elevate#691] opened 2018-11-15 14:18 UTC
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: _____
  * Chrome/Opera/Chromium version: _____
  * OS version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be usefull to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by aprokop** [comment] 2018-11-15 15:07
Duplicate of #682 and others. Please consult release notes or #579 for the explanation. In short, the correct calculation of Form is based on yesterday's fitness and fatigue.

**Closed** 2018-11-16 13:39 UTC

**Comment by thomaschampagne** [comment] 2018-11-16 17:46
I may put that in the FAQ...
