### ISSUE TITLE
strava activity display broken in all browsers after installing elevate in chrome

### ISSUE THREAD

**Issue by drumphil9901** [thomaschampagne/elevate#991] opened 2020-08-13 14:11 UTC
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/elevate/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/elevate/issues?

### Step 2: Describe your environment

  * Plugin version: _6.16.2 stable
  * Chrome/Opera/Chromium version: _chrome 84.0.4147.105
  * OS version: _win 10 pro 2004 19041.388
  
### Step 3: Describe the problem:

since installing the elevate plugin into chrome on my win 10 pc, whenever i use strava web in any browser in windows or android, the activities wont display the track on the map or the pace analysis

#### Steps to reproduce:

  1. __install elevate in chrome and sych activities
  2. __use strava web in firefox (no elevate installed)
  3. _open an activity
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?

expected no issues - does the synch load "infect" my strava account?
everything displays fine in the strava android app
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your Elevate synced athlete activities can be useful to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by faina09** [comment] 2020-08-13 18:26
When you sync data for Elevate the first time, all allowed fetch for your Strava account are used.
Simply wait 2-3 hour and everything will return to normal status.

**Comment by drumphil9901** [comment] 2020-08-13 22:58
Ok so it is load related...? Thanks, I'll wait a will then. I guess this potential needs to be more clearly stated on the synch window *before* you start. 
An option to throttle it or to select a smaller batch instead of 400 would be handy

**Comment by drumphil9901** [comment] 2020-08-13 23:30
hmmmm so 9 hours ago it was an issue... and is still an issue - i have checked strava in firefox (no elevate) and activities will still not load the track on the map or display pace analysis. i have not been into elevate this morning so have not initiated any new synch requests

**Comment by faina09** [comment] 2020-08-14 05:40
The issue is indipendent from the browser, it depends only from the account/athlete id that performed the sync.
You should check if any message is show in firefox console (ctrl+shift+K in firefox windows).
I am still almost sure that you will find a "Too many request" message; this limitation will be reset after some time (9h seems ideneed too much...).

As you found, the issue seems to be a duplicate of #970

**Closed** 2020-10-24 08:23 UTC
Labels: wontfix
